-- MySQL Script generated by MySQL Workbench
-- Tue Jun 20 16:24:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mapetiteepicerie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mapetiteepicerie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mapetiteepicerie` DEFAULT CHARACTER SET utf8 ;
USE `mapetiteepicerie` ;

-- -----------------------------------------------------
-- Table `mapetiteepicerie`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mapetiteepicerie`.`categories` (
  `categorie` VARCHAR(45) NOT NULL,
  `photo_cat` VARCHAR(45) NULL DEFAULT NULL,
  `essai` VARCHAR(45) NULL,
  PRIMARY KEY (`categorie`),
  UNIQUE INDEX `categorie` (`categorie` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mapetiteepicerie`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mapetiteepicerie`.`utilisateurs` (
  `ID_util` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NULL,
  `adresse1` VARCHAR(45) NOT NULL,
  `adresse2` VARCHAR(45) NULL DEFAULT NULL,
  `CP` INT(11) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NULL DEFAULT NULL,
  `mobile` VARCHAR(45) NULL DEFAULT NULL,
  `heure_pref` TIME NULL DEFAULT NULL,
  `points_fid` INT(11) NULL DEFAULT '0',
  `date_points_fid` DATE NULL DEFAULT NULL,
  `droits_acces` VARCHAR(15) NOT NULL DEFAULT 'utilisateur',
  PRIMARY KEY (`ID_util`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mapetiteepicerie`.`commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mapetiteepicerie`.`commandes` (
  `ID_cde` INT(11) NOT NULL AUTO_INCREMENT,
  `date_com` DATE NOT NULL,
  `date_livr` DATE NULL DEFAULT NULL,
  `heure_livr` TIME NULL DEFAULT NULL,
  `points_fidelite` INT(11) NULL DEFAULT NULL,
  `id_util` INT(11) NOT NULL,
  `utilisateurs_ID_util` INT(11) NOT NULL,
  `utilisateurs_panier_ID_panier` INT(11) NOT NULL,
  PRIMARY KEY (`ID_cde`, `id_util`, `utilisateurs_ID_util`, `utilisateurs_panier_ID_panier`),
  INDEX `fk_commandes_utilisateurs_idx` (`id_util` ASC),
  INDEX `fk_commandes_utilisateurs1_idx` (`utilisateurs_ID_util` ASC, `utilisateurs_panier_ID_panier` ASC),
  CONSTRAINT `fk_commandes_utilisateurs1`
    FOREIGN KEY (`utilisateurs_ID_util`)
    REFERENCES `mapetiteepicerie`.`utilisateurs` (`ID_util`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mapetiteepicerie`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mapetiteepicerie`.`produits` (
  `ID_prod` INT(11) NOT NULL AUTO_INCREMENT,
  `descriptif` LONGTEXT NULL DEFAULT NULL,
  `poids_volume` VARCHAR(45) NULL DEFAULT NULL,
  `unites` VARCHAR(45) NULL DEFAULT NULL,
  `marque` VARCHAR(45) NULL DEFAULT NULL,
  `photo1` VARCHAR(45) NULL DEFAULT NULL,
  `categorie` VARCHAR(45) NOT NULL,
  `ingredients` LONGTEXT NULL,
  `code_barre` VARCHAR(13) NULL,
  `categories_categorie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_prod`, `categories_categorie`),
  INDEX `fk_produits_categories1_idx` (`categories_categorie` ASC),
  CONSTRAINT `fk_produits_categories1`
    FOREIGN KEY (`categories_categorie`)
    REFERENCES `mapetiteepicerie`.`categories` (`categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mapetiteepicerie`.`commercant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mapetiteepicerie`.`commercant` (
  `nom_commercial` VARCHAR(100) NOT NULL,
  `siret` VARCHAR(45) NULL,
  `utilisateurs_ID_util` INT(11) NOT NULL,
  PRIMARY KEY (`utilisateurs_ID_util`),
  INDEX `fk_commercant_utilisateurs1_idx` (`utilisateurs_ID_util` ASC),
  CONSTRAINT `fk_commercant_utilisateurs1`
    FOREIGN KEY (`utilisateurs_ID_util`)
    REFERENCES `mapetiteepicerie`.`utilisateurs` (`ID_util`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mapetiteepicerie`.`stock_produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mapetiteepicerie`.`stock_produits` (
  `produits_ID_prod` INT(11) NOT NULL,
  `prix` DECIMAL(10,2) NULL DEFAULT NULL,
  `prix_old` DECIMAL(10,2) NULL DEFAULT NULL,
  `promo` VARCHAR(15) NULL DEFAULT 'Normal',
  `nouveau` VARCHAR(3) NULL DEFAULT 'non',
  `stock` INT NULL,
  `commercant_utilisateurs_ID_util` INT(11) NOT NULL,
  PRIMARY KEY (`produits_ID_prod`, `commercant_utilisateurs_ID_util`),
  INDEX `fk_stock_produits_produits1_idx` (`produits_ID_prod` ASC),
  INDEX `fk_stock_produits_commercant1_idx` (`commercant_utilisateurs_ID_util` ASC),
  CONSTRAINT `fk_stock_produits_produits1`
    FOREIGN KEY (`produits_ID_prod`)
    REFERENCES `mapetiteepicerie`.`produits` (`ID_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_produits_commercant1`
    FOREIGN KEY (`commercant_utilisateurs_ID_util`)
    REFERENCES `mapetiteepicerie`.`commercant` (`utilisateurs_ID_util`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mapetiteepicerie`.`commandes_has_produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mapetiteepicerie`.`commandes_has_produits` (
  `commandes_ID_cde` INT(11) NOT NULL,
  `commandes_id_util` INT(11) NOT NULL,
  `produits_ID_prod` INT(11) NOT NULL,
  PRIMARY KEY (`commandes_ID_cde`, `commandes_id_util`, `produits_ID_prod`),
  INDEX `fk_commandes_has_produits_produits1_idx` (`produits_ID_prod` ASC),
  INDEX `fk_commandes_has_produits_commandes1_idx` (`commandes_ID_cde` ASC, `commandes_id_util` ASC),
  CONSTRAINT `fk_commandes_has_produits_commandes1`
    FOREIGN KEY (`commandes_ID_cde` , `commandes_id_util`)
    REFERENCES `mapetiteepicerie`.`commandes` (`ID_cde` , `id_util`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_has_produits_produits1`
    FOREIGN KEY (`produits_ID_prod`)
    REFERENCES `mapetiteepicerie`.`produits` (`ID_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
