-- MySQL Script generated by MySQL Workbench
-- Tue Jun  6 16:12:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateurs` (
  `ID_util` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `adresse1` VARCHAR(45) NULL,
  `adresse2` VARCHAR(45) NULL,
  `CP` INT NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `heure pref` TIME NULL,
  `points_fid` INT NULL DEFAULT 0,
  `date_points_fid` DATE NULL,
  PRIMARY KEY (`ID_util`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commandes` (
  `ID_cde` INT NOT NULL AUTO_INCREMENT,
  `date_com` DATE NOT NULL,
  `date_livr` DATE NULL,
  `heure_livr` TIME NULL,
  `commentaire` LONGTEXT NULL,
  `id_util` INT NOT NULL,
  PRIMARY KEY (`ID_cde`, `id_util`),
  INDEX `fk_commandes_utilisateurs_idx` (`id_util` ASC),
  CONSTRAINT `fk_commandes_utilisateurs`
    FOREIGN KEY (`id_util`)
    REFERENCES `mydb`.`utilisateurs` (`ID_util`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `ID_cat` INT NOT NULL AUTO_INCREMENT,
  `categorie` VARCHAR(45) NOT NULL,
  `photo_cat` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_cat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produits` (
  `ID_prod` INT NOT NULL AUTO_INCREMENT,
  `descriptif` LONGTEXT NULL,
  `poids_volume` VARCHAR(45) NULL,
  `unites` VARCHAR(45) NULL,
  `marque` VARCHAR(45) NULL,
  `prix` DECIMAL NOT NULL,
  `photo1` VARCHAR(45) NULL,
  `photo2` VARCHAR(45) NULL,
  `attente` TINYINT NULL,
  `promo` TINYINT NULL,
  `nouveau` TINYINT NULL,
  `id_cat` INT NOT NULL,
  PRIMARY KEY (`ID_prod`, `id_cat`),
  INDEX `fk_produits_categories1_idx` (`id_cat` ASC),
  CONSTRAINT `fk_produits_categories1`
    FOREIGN KEY (`id_cat`)
    REFERENCES `mydb`.`categories` (`ID_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`commandes_produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commandes_produits` (
  `prix` DECIMAL NOT NULL,
  `quantité` INT NOT NULL,
  `points_fidelite` INT NULL,
  `id_cde` INT NOT NULL,
  `id_prod` INT NOT NULL,
  PRIMARY KEY (`id_cde`, `id_prod`),
  INDEX `fk_commandes_has_produits_produits1_idx` (`id_prod` ASC),
  INDEX `fk_commandes_has_produits_commandes1_idx` (`id_cde` ASC),
  CONSTRAINT `fk_commandes_has_produits_commandes1`
    FOREIGN KEY (`id_cde`)
    REFERENCES `mydb`.`commandes` (`ID_cde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_has_produits_produits1`
    FOREIGN KEY (`id_prod`)
    REFERENCES `mydb`.`produits` (`ID_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `ID_login` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `droits_acces` INT NOT NULL,
  `token` VARCHAR(45) NULL,
  `date_token` DATE NULL,
  `id_util` INT NOT NULL,
  PRIMARY KEY (`ID_login`, `id_util`),
  INDEX `fk_login_utilisateurs1_idx` (`id_util` ASC),
  CONSTRAINT `fk_login_utilisateurs1`
    FOREIGN KEY (`id_util`)
    REFERENCES `mydb`.`utilisateurs` (`ID_util`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`commercant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commercant` (
  `ID_commercant` INT NOT NULL AUTO_INCREMENT,
  `textes_annonce` MEDIUMTEXT NULL,
  `textes_email` MEDIUMTEXT NULL,
  `id_login` INT NOT NULL,
  PRIMARY KEY (`ID_commercant`, `id_login`),
  INDEX `fk_commercant_login1_idx` (`id_login` ASC),
  CONSTRAINT `fk_commercant_login1`
    FOREIGN KEY (`id_login`)
    REFERENCES `mydb`.`login` (`ID_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
